/**
 * Alipay.com Inc.
 * Copyright (c) 2004‐2020 All Rights Reserved.
 */
package com.mitrais.bootcamp.view.screen.impl;

import com.mitrais.bootcamp.domain.*;
import com.mitrais.bootcamp.enums.ATMConstant;
import com.mitrais.bootcamp.enums.ScreenCode;
import com.mitrais.bootcamp.service.integration.minibank.Transaction;
import com.mitrais.bootcamp.util.ATMUtil;
import com.mitrais.bootcamp.view.screen.Screen;

import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;

/**
 * @author Aji Atin Mulyadi
 * @version $Id: FundTransferScreenImpl.java, v 0.1 2020‐07‐22 20:28 Aji Atin Mulyadi Exp $$
 */
public class FundTransferScreenImpl implements Screen {

    private Transaction fundTransferService;
    private ATMData userDetail;
    private FundTransferScreenDataResponse screenDataResponse;

    public FundTransferScreenImpl(Transaction fundTransferService) {
        this.fundTransferService = fundTransferService;
    }

    @Override
    public ATMSimulationResult<BaseScreenResponseData> renderScreen(ScreenRequestData requestData) {
        ATMSimulationResult<BaseScreenResponseData> response;
        response = new ATMSimulationResult<>();
        screenDataResponse = new FundTransferScreenDataResponse();

        FundTransferScreenDataRequest screenDataRequest = (FundTransferScreenDataRequest) requestData;
        userDetail = screenDataRequest.getUserDetail();
        screenDataResponse.setUserDetail(userDetail);

        String inputDestAccount = getFundTransferValue(ATMConstant.DESTINATION_ACCOUNT_FIELD_NAME.getValue());
        if(inputDestAccount.isEmpty()){
            screenDataResponse.setScreenCode(ScreenCode.TRANSACTION_SCREEN);
            response.setSuccess(true);
            response.setObject(screenDataResponse);
            return response;
        }

        String inputTrfAmount = getFundTransferValue(ATMConstant.TRANSFER_AMOUNT_FIELD_NAME.getValue());
        if(inputTrfAmount.isEmpty()){
            screenDataResponse.setScreenCode(ScreenCode.TRANSACTION_SCREEN);

            response.setSuccess(true);
            response.setObject(screenDataResponse);
            return response;
        }

        long refNumber = refNumberScreen();

        fundTransferConfirmationScreen(inputDestAccount, inputTrfAmount, refNumber);

        response.setSuccess(true);
        response.setObject(screenDataResponse);

        return response;
    }

    public String getFundTransferValue(String fieldName){
        System.out.println();
        Scanner scanner = new Scanner(System.in);
        System.out.println("Please enter "+fieldName+" and press enter to continue or \n" +
                "press enter to go back to Transaction : ");

        return scanner.nextLine();
    }

    public static long refNumberScreen() {
        System.out.println();
        Scanner scanner = new Scanner(System.in);
        System.out.print("Reference Number: (This is an autogenerated random 6 digits number)\n" +
                "press enter to continue");
        String opt = scanner.nextLine();
        if (!opt.isEmpty()) {
            refNumberScreen();
        }
        return ATMUtil.getRandomIntegerBetweenRange(100000, 999999);
    }

    public void fundTransferConfirmationScreen(String destAccount, String trfAmount, long refNo){
        System.out.println();
        System.out.print("Transfer Confirmation\n" +
                "Destination Account : " + destAccount + "\n" +
                "Transfer Amount     : $" + trfAmount + "\n" +
                "Reference Number    : " + refNo + "\n" +
                "\n" +
                "1. Confirm Trx\n" +
                "2. Cancel Trx\n" +
                "Choose option[2]:");
        Scanner scanner = new Scanner(System.in);
        try {
            int opt = scanner.nextInt();
            if (opt == 1) {

                List<String> errors = validateFundTransferFields(destAccount, refNo);
                if(errors.size() > 0){
                    for (String error : errors) {
                        System.out.println(error);
                    }

                    screenDataResponse.setScreenCode(ScreenCode.FUNDTRANSFER_SCREEN);

                }else {
                    doFundTransfer(destAccount, trfAmount, refNo);
                }

            } else if (opt == 2) {
                screenDataResponse.setScreenCode(ScreenCode.TRANSACTION_SCREEN);
            } else {
                System.out.println("Please input valid option ...");
                fundTransferConfirmationScreen(destAccount, trfAmount, refNo);
            }
        } catch (Exception e) {
            System.out.println("Please input valid option ...");
            fundTransferConfirmationScreen(destAccount, trfAmount, refNo);
        }

    }

    public static List<String> validateFundTransferFields(String destAccount, long refNo){
        List<String> errors = new ArrayList<>();
        boolean isValidAccountNumberType = ATMUtil.validateFormat(destAccount, ATMConstant.ACCOUNT_NUMBER_TYPE_REGEX.getValue());
        if(!isValidAccountNumberType){
            errors.add("Account Number should only contains numbers");
        }

        boolean isValidAccountNumberLength = ATMUtil.validateFormat(destAccount, ATMConstant.ACCOUNT_NUMBER_LENGTH_REGEX.getValue());
        if(!isValidAccountNumberLength){
            errors.add("Account Number should have 6 digits length");
        }

        boolean isValidAmount = ATMUtil.validateFormat(destAccount, ATMConstant.AMOUNT_TYPE_REGEX.getValue());
        if(!isValidAmount){
            errors.add("Invalid amount");
        }

        if(refNo == 0){
            errors.add("Invalid  Reference Number");
        }
        return errors;
    }

    private void doFundTransfer(String destAccount, String trfAmount, long refNo){

        FundTransferRequest fundTransferRequest = new FundTransferRequest();
        fundTransferRequest.setDestAccountNumber(Long.parseLong(destAccount));
        fundTransferRequest.setSrcAccountNumber(userDetail.getAccountNumber());
        fundTransferRequest.setRefNumber(refNo);
        fundTransferRequest.setAmount(Long.parseLong(trfAmount));

        ATMSimulationResult<Transactionable> fundTransferResponse = fundTransferService.execute(fundTransferRequest);
        if(!fundTransferResponse.isSuccess()){
            System.out.println(fundTransferResponse.getErrorContext().getErrorMessage());
            System.out.println();
            screenDataResponse.setScreenCode(ScreenCode.FUNDTRANSFER_SCREEN);
        }else {
            FundTransferResponse fundTransferResponseObj = (FundTransferResponse) fundTransferResponse.getObject();
            userDetail = fundTransferResponseObj.getSrcAccount();
            summaryFunTransfer(destAccount, trfAmount, refNo);
        }
    }

    public void summaryFunTransfer(String acc, String amount, long ref) {
        Scanner scanner = new Scanner(System.in);
        System.out.println();
        System.out.print("Fund Transfer Summary\n" +
                "Destination Account : " + acc + "\n" +
                "Transfer Amount     : $" + amount + "\n" +
                "Reference Number    : " + ref + "\n" +
                "Balance             : $" + userDetail.getBalance() + "\n" +
                "\n" +
                "1. Transaction\n" +
                "2. Exit\n" +
                "Choose option[2]:");
        String opt = scanner.nextLine();
        if (opt.isEmpty()) {
            screenDataResponse.setScreenCode(ScreenCode.WELCOME_SCREEN);
        } else {
            try {
                int option = Integer.parseInt(opt);
                if (option == 1) {
                    screenDataResponse.setScreenCode(ScreenCode.TRANSACTION_SCREEN);
                } else {
                    screenDataResponse.setScreenCode(ScreenCode.WELCOME_SCREEN);
                }
            } catch (Exception e) {
                screenDataResponse.setScreenCode(ScreenCode.FUNDTRANSFER_SCREEN);
            }
        }
    }


}